name: Build and deploy Node.js app to Azure Web App - Beawareapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: Beawareapp
  AZURE_WEBAPP_PACKAGE_PATH: dist
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (client + server)
        run: npm run build

      # ---- Azure login (OIDC) ----
      - name: 'Az Login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35E5315EDCBD454A89028DC816115969 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_35E5315EDCBD454A89028DC816115969 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35E5315EDCBD454A89028DC816115969 }}

      # Minimal infra tweak so the container runs the compiled JS (not TS with tsx)
      - name: Set startup command (Linux Web App)
        run: |
          APP_ID=$(az webapp show --name $AZURE_WEBAPP_NAME --query id -o tsv)
          az webapp config set --ids "$APP_ID" --startup-file "node dist/server/index.js"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Logout
        if: always()
        run: az logout
