name: Deploy BeAware App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: beawareapp-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"
  AZURE_WEBAPP_NAME: beaware-app           # <-- change to your Azure Web App name
  PACKAGE_PATH: .                          # deploy the repo root (includes node_modules + dist)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Cache npm modules (extra)
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies (clean)
        run: npm ci

      - name: Build (client + server)
        run: npm run build

      # Optional: if your server serves the client build from /dist, keep both under the same /dist folder
      # Ensure tsconfig outDir -> dist/server and Vite outputs to dist/
      # If your Vite config outputs to a different folder, adjust here.

      - name: Prune dev dependencies for production
        run: npm prune --production

      # (Optional) Confirm what will be deployed
      - name: List key build outputs
        run: |
          echo "Repo root:"
          ls -la
          echo "dist tree:"
          if [ -d dist ]; then ls -la dist; fi
          if [ -d dist/server ]; then ls -la dist/server; fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PACKAGE_PATH }}

      # Optional: warm up the app after deploy (ignores failure)
      - name: Warm up
        run: |
          sleep 5
          echo "Warming up..."
          curl -I "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" || true
