name: Build and deploy Node.js app to Azure Web App - Beawareapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Create deployment package
        run: |
          mkdir deploy
          cp -r dist/* deploy/
          cp package.json deploy/
          cp -r node_modules deploy/

      - name: Zip deploy folder
        run: |
          cd deploy
          zip -r ../deploy.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Beawareapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip
