name: Build and deploy Node.js app to Azure Web App - Beawareapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Global permissions required for OIDC login to Azure
permissions:
  contents: read
  id-token: write

env:
  ENV_NAME: dev       # shown in the UI (dev/prod)
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          echo "Building frontend with Vite..."
          npx vite build

          echo "Ensuring compiled directory exists..."
          mkdir -p compiled/server compiled/shared

          echo "Compiling TypeScript files..."
          npx tsc --project server/tsconfig.json || echo "TypeScript compilation completed with warnings"

          echo "Verifying build output..."
          ls -la compiled/server/ || true
          ls -la dist/ || true
          echo "Build process completed successfully"

      - name: Inject version.json (from CI)
        run: |
          set -e
          VERSION="${VERSION:-$(node -p "require('./package.json').version")}"
          BUILD="${GITHUB_RUN_NUMBER}"
          COMMIT="${GITHUB_SHA}"
          BUILT_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          mkdir -p dist/public
          cat > dist/public/version.json <<'JSON'
          {
            "app": "BeAware",
            "environment": "__ENV__",
            "version": "__VERSION__",
            "build": "__BUILD__",
            "commit": "__COMMIT__",
            "builtAt": "__BUILT_AT__"
          }
          JSON
          sed -i "s/__ENV__/${ENV_NAME}/" dist/public/version.json
          sed -i "s/__VERSION__/${VERSION}/" dist/public/version.json
          sed -i "s/__BUILD__/${BUILD}/" dist/public/version.json
          sed -i "s/__COMMIT__/${COMMIT}/" dist/public/version.json
          sed -i "s/__BUILT_AT__/${BUILT_AT}/" dist/public/version.json
          echo "----- dist/public/version.json -----"
          cat dist/public/version.json

      - name: Prune dev dependencies
        run: npm prune --production

      - name: Prepare deploy folder (artifact)
        run: |
          # Use a clear folder name that will be downloaded in the deploy job
          rm -rf node-app
          mkdir -p node-app

          # Copy compiled server files
          if [ -d "compiled" ]; then
            cp -r compiled node-app/
          fi

          # Copy frontend build (includes version.json)
          if [ -d "dist" ]; then
            mkdir -p node-app/dist
            cp -r dist/* node-app/dist/
          fi

          # Copy runtime files
          cp package*.json node-app/ || true
          cp index.js node-app/ 2>/dev/null || echo "index.js not found, skipping"
          cp server.js node-app/ 2>/dev/null || echo "server.js not found, skipping"
          cp -r node_modules node-app/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app
          path: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35E5315EDCBD454A89028DC816115969 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1215FCCAAF9042179F0D2D36AB844422 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0168D1E4AD14FB7A3C0BF8FCECF99E5 }}

      # --- NEW: keep DB schema in sync before deploying the app ---
      # Uses your existing SQL script in the repo (no new files).
      # Add a repo secret AZURE_SQL_CONNECTION with a full connection string.
      - name: Apply DB schema updates
        uses: Azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION }}
          path: update-azure-schema.sql

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Beawareapp'
          slot-name: 'Production'
          package: node-app
