name: Build and deploy Node.js app to Azure Web App - Beawareapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Global permissions required for OIDC login to Azure
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: |
          echo "Building frontend with Vite..."
          npx vite build
          echo "Ensuring compiled directory exists..."
          mkdir -p compiled/server compiled/shared
          echo "Compiling TypeScript files..."
          npx tsc --project server/tsconfig.json || echo "TypeScript compilation completed with warnings"
          echo "Verifying build output..."
          ls -la compiled/server/
          ls -la dist/
          echo "Build process completed successfully"

      - name: Prune dev dependencies
        run: npm prune --production

      - name: Prepare deploy folder
        run: |
          mkdir deploy
          # Copy compiled server files
          if [ -d "compiled" ]; then
            cp -r compiled/* deploy/
          fi
          # Copy frontend build files
          if [ -d "dist" ]; then
            mkdir -p deploy/dist
            cp -r dist/* deploy/dist/
          fi
          # Copy necessary configuration files
          cp package*.json deploy/
          cp index.js deploy/ || echo "index.js not found, skipping"
          cp server.js deploy/ || echo "server.js not found, skipping"
          # Copy minimal node_modules (production only)
          cp -r node_modules deploy/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35E5315EDCBD454A89028DC816115969 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1215FCCAAF9042179F0D2D36AB844422 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0168D1E4AD14FB7A3C0BF8FCECF99E5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Beawareapp'
          slot-name: 'Production'
          package: .
