name: Build & Deploy (PROD)

on:
  push:
    branches: [ production ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  NODE_VERSION: '20.x'
  WEBAPP_NAME: 'Beaware-Prod'    # your PROD App Service
  SLOT_NAME: 'Production'
  ARTIFACT_NAME: 'node-app'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci || npm install
      - name: Build
        run: |
          npx vite build
          mkdir -p compiled/server compiled/shared
          npx tsc --project server/tsconfig.json || echo "tsc warnings ignored"
      - run: npm prune --production

      - name: Pack artifact
        run: |
          rm -rf deploy && mkdir deploy
          [ -d compiled ] && cp -r compiled/* deploy/
          if [ -d dist ]; then mkdir -p deploy/dist && cp -r dist/* deploy/dist/; fi
          cp package*.json deploy/ || true
          cp index.js deploy/ 2>/dev/null || true
          cp server.js deploy/ 2>/dev/null || true
          cp -r node_modules deploy/

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_35E5315EDCBD454A89028DC816115969 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1215FCCAAF9042179F0D2D36AB844422 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F0168D1E4AD14FB7A3C0BF8FCECF99E5 }}

      - name: Deploy to Azure Web App (PROD)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          package: .
